### ISSUE TITLE
Setting multiple types for ArgOption of vector

### ISSUE THREAD

**Issue by RandyParedis** [ZhreShold/zupply#14]
Hello,

First of all, I love the ease and simplicity of this library; thank you for creating it.

Now, I have a simple project that I would like to have a certain flag, let's say `--convert` (or `-c`) that takes exactly four arguments (a directory and three files). Can I add type information in such a way that I get the following info when calling `get_help`?
```Usage: project [-c <directory> <file1> <file2> <file3>]```

Currently I get
```Usage: project [-c <directory file1 file2 file3> <directory file1 file2 file3> <directory file1 file2 file3>]```
which is not quite that helpful for a user, but also strange seeing as I don't see all arguments. (Shouldn't [zupply.cpp:12488](https://github.com/zhreshold/zupply/blob/master/src/zupply.cpp#L12488) be ```for (int i = 2; i < min_+1; ++i)```?

I sort of know/understand how to fix it in the `ArgOption::get_short_help()` function, but didn't want to make a pull request if this functionality already exists.

**EDIT:** Within the same context, I noticed an `ArgParser Error` is not being called for an invalid amount of arguments, unless I use `-c` multiple times. (Shouldn't [zupply.cpp:12809](https://github.com/zhreshold/zupply/blob/master/src/zupply.cpp#L12809) be ```if (o.count_ >= 1 && o.min_ > o.size_)```?)

**Comment by zhreshold** [comment]
@RandyParedis Thanks for the feedback and good catches!
Regarding the get_help format,  you are welcome to propose a more elegent way to handle multiple arguments. A PR is very welcome!
